### ISSUE TITLE
Two success notifications after saving plugin settings

### ISSUE THREAD

**Issue by shawnhooper** [trustedlogin/trustedlogin-vendor#36]
Filled out the account id and api keys.  Got two confirmation notifications in the dashboard:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/2073284/80872388-99f61d00-8c7f-11ea-86dc-f50f1d86555e.png">

This was in the **refactor** branch.

**Comment by inztinkt** [comment]
Was able to reproduce on fresh install.
