### ISSUE TITLE
Add button to reset access keys

### ISSUE THREAD

**Issue by zackkatz** [trustedlogin/trustedlogin-vendor#46]
- Needs double opt-in, like GitHub "DELETE" dialog
- The double opt-in MUST NOT process if the dialog doesn't load. Too many times there are JS errors on a site.

When successful: 

- Pings the SaaS will be notified that a reset has occurred.
- Regenerates the encryption keys.

**Comment by inztinkt** [comment]
> The double opt-in MUST NOT process if the dialog doesn't load. Too many times there are JS errors on a site.

Can you show me a screenshot of the GH dialog? Want to confirm if we're using an alert/modal or inline notice.

**Comment by zackkatz** [comment]
@inztinkt 

## 1. Have "Danger Zone"-like section
![](https://i.gravityview.co/G25Ayg+)

## 2. Button shows modal

- The modal requires typing confirmation text.
- The confirm button is disabled until the confirmation text is typed in properly

![](https://i.gravityview.co/N0WXA0+)

## 3. Forces confirm password

Not sure this would work in WP, but it's one more step, since this is a big change. I think this prevents a "person walked away from their computer without locking the screen" attack.

![](https://i.gravityview.co/pGbPgS+)

## 4. Show confirmation that the [keys were cycled]

![](https://i.gravityview.co/EtEJ4C+)

**Comment by inztinkt** [comment]
@zackkatz For Step 3, should they be asked to log back into their WP site or TL SaaS?

**Comment by zackkatz** [comment]
@inztinkt For now, let's skip Step 3 and make sure to check nonces when completing the cycling.

**Comment by inztinkt** [comment]
<img width="1552" alt="Screenshot 2020-08-03 15 15 43" src="https://user-images.githubusercontent.com/251348/89218585-54a5fc00-d59c-11ea-848a-db17e7cac93e.png">

@zackkatz Should 'danger zone' go on the bottom of the settings page or on it's own settings page?

**Comment by inztinkt** [comment]
@zackkatz I've built this to leverage the browsers' usual confirm dialogue. 

I can certainly add the secondary confirmation and warning if you'd like. Just need to confirm what the UX/output/etc should contain and if you want it in a modal/alert/etc.

**Comment by zackkatz** [comment]
> @zackkatz Should 'danger zone' go on the bottom of the settings page or on it's own settings page?

Let's wait for Tracy to weigh in on this.

**Comment by zackkatz** [comment]
Closing for now—it'll need redesign.
