### ISSUE TITLE
handle accessKey-based redirects when <1 siteIds are returned from SaaS

### ISSUE THREAD

**Issue by inztinkt** [trustedlogin/trustedlogin-vendor#47]
A single accessKey (or licenseKey) may return more than 1 siteId.

This should be handled in a way that gives support agent a way to pick the right site.
(May include decrypting url attribute of envelope to show)

Needs to be implemented for:
- [ ] Access Key login via Vendor Plugin
- [ ] Helpdesk widget login (to show the site urls for each siteId)

**Comment by zackkatz** [comment]
@inztinkt This needs to be implemented sooner than I thought. I've encountered this in testing.

How long do you think this would take?

**Comment by inztinkt** [comment]
I can schedule it in now. So to confirm, iff we get more than 1 siteId from an accessKey, then fetch each envelope, and decrypt each of them to get the siteurl values.

Should the links from this still go through the vendor-side redirect, or point straight to the client-side endpoints?

Arguments for the vendor-side redirect:
- still gets all the logging and etc we have in place on vendor-side
- the link (if copied/pasted/shared) still checks authentication before redirecting to customers auto-login link

Arguments against vendor-side redirect:
- Slower as we're doing decrypting n+1 envelopes (where n = number of siteIds) before the support agent is logged in.

**Comment by zackkatz** [comment]
@inztinkt Still vendor-side.

**Comment by inztinkt** [comment]
Got it. Thought so, just wanted to confirm as you know how slow decryption can be sometimes.
